# Generated by Django 5.2.4 on 2025-07-11 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_centre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('PREV', 'Prévention'), ('SYMP', 'Symptômes'), ('TRAIT', 'Traitement'), ('URG', 'Urgence')], max_length=5)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='articles/')),
                ('auteur', models.CharField(blank=True, max_length=100)),
                ('mots_cles', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Article de Santé',
                'verbose_name_plural': 'Articles de Santé',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='CentreMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('CS', 'Centre de Santé'), ('HP', 'Hôpital'), ('PS', 'Poste de Santé')], max_length=2)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('services', models.TextField(blank=True, help_text='Services offerts, séparés par des virgules')),
            ],
            options={
                'verbose_name': 'Centre Médical',
                'verbose_name_plural': 'Centres Médicaux',
                'ordering': ['nom'],
            },
        ),
        migrations.DeleteModel(
            name='Centre',
        ),
        migrations.AlterModelOptions(
            name='rappel',
            options={'ordering': ['heure'], 'verbose_name': 'Rappel Médical', 'verbose_name_plural': 'Rappels Médicaux'},
        ),
        migrations.AlterModelOptions(
            name='recherche',
            options={'ordering': ['-date'], 'verbose_name': 'Recherche Médicale', 'verbose_name_plural': 'Recherches Médicales'},
        ),
        migrations.RemoveField(
            model_name='recherche',
            name='texte',
        ),
        migrations.AddField(
            model_name='rappel',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rappel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rappel',
            name='periodique',
            field=models.CharField(choices=[('PONCTUEL', 'Ponctuel'), ('QUOTIDIEN', 'Quotidien'), ('HEBDOMADAIRE', 'Hebdomadaire')], default='PONCTUEL', max_length=20),
        ),
        migrations.AddField(
            model_name='rappel',
            name='titre',
            field=models.CharField(default='Rappel médical', max_length=200),
        ),
        migrations.AddField(
            model_name='recherche',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='symptomes/'),
        ),
        migrations.AddField(
            model_name='recherche',
            name='reponse_bam',
            field=models.TextField(blank=True, verbose_name='Réponse (Bambara)'),
        ),
        migrations.AddField(
            model_name='recherche',
            name='reponse_mp3',
            field=models.FileField(blank=True, null=True, upload_to='reponses/'),
        ),
        migrations.AddField(
            model_name='recherche',
            name='symptomes_bam',
            field=models.TextField(default='Aucun symptôme', verbose_name='Symptômes (Bambara)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recherche',
            name='symptomes_fr',
            field=models.TextField(blank=True, verbose_name='Symptômes (Français)'),
        ),
        migrations.AlterField(
            model_name='rappel',
            name='medicament',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rappel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recherches', to=settings.AUTH_USER_MODEL),
        ),
    ]
