# Generated by Django 5.2.4 on 2025-07-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_centremedical_delete_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherche',
            name='symptomes_bam',
            field=models.TextField(default='Aucun symptôme', verbose_name='Symptômes (Bambara)'),
        ),
    ]
